# Broadcasting

https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html

El concepto de broadcasting se usa para entender como NumPy realiza las operaciones entre arreglos (vectores, matrices, tensores) de diferente tamaño. Sujeto a ciertas restricciones, el arreglo más pequeño es “difundido” (¡?) a través del arreglo más grande, para que de esta forma sean compatibles en tamaño.

El broadcasting muchas veces conduce a una implementación más eficiente de los algoritmos ya que proporciona un medio para la vectorización de operaciones de modo que los bucles se realicen en C y no en Python. Sin embargo pueden existir situaciones en que utilizar broadcasting sea ineficiente, debido a un uso ineficiente de la memoria.

In [1]:
import numpy as np

M = np.array([[1, 6, 2],
              [4, 2, 3],
              [1, 4, 2]])

v = np.array([5, 2, 1])

print(M + v)

[[6 8 3]
 [9 4 4]
 [6 6 3]]


### Reglas generales de broadcasting

Cuando se opera en dos matrices, NumPy compara sus formas por elementos. Comienza con las dimensiones finales y avanza. Dos dimensiones son compatibles cuando:

* 1. Son iguales, o
* 2. Uno de ellos es 1

Si no se cumplen estas condiciones, se lanza una excepción, lo que indica que las matrices tienen formas incompatibles. El tamaño de la matriz resultante es el tamaño máximo a lo largo de cada dimensión de las matrices de entrada. `ValueError: frames are not aligned`